# Generated by Django 4.2.1 on 2023-05-14 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 18, 56, 0, 202338, tzinfo=datetime.timezone.utc)),
        ),
    ]
