# Generated by Django 4.2.1 on 2023-05-15 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_passwordresetcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 12, 23, 49, 621932, tzinfo=datetime.timezone.utc)),
        ),
    ]
