# Generated by Django 4.2.1 on 2023-05-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='topicfollow',
            options={'verbose_name_plural': 'Topics Follow'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'User statuses'},
        ),
        migrations.AlterUniqueTogether(
            name='topicfollow',
            unique_together=set(),
        ),
    ]
